# Project information:
site_name: ObjeX
# site_url: https://


# Repository:
repo_name: 2024.1-ObjeX
repo_url: https://github.com/mdsreq-fga-unb/2024.1-ObjeX


extra_css:
  - stylesheets/extra.css
theme:
  custom_dir: overrides
  logo: assets/logo1.png
  favicon: assets/logo1.png
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - announce.dismiss
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - search.share
    - toc.follow
  language: pt
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: green
  font:
    text: Roboto
    code: Roboto Mono


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mdsreq-fga-unb/2024.1-ObjeX


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons


nav:
  - História da Facção: index.md
  - Visão Geral do Produto:
    - Problema: produto-problema.md
    - Declaração de Posição do Produto: produto-posicao.md
    - Objetivos do Produto: produto-objetivos.md
    - Tecnologias a Serem Utilizadas: produto-tecnologias.md
  - Processo de Desenvolvimento de Software: processo-desenvolvimento.md
  - Visão Geral do Projeto: projeto-visao.md
  - Missão 1:
    - Entregas: entrega-missao1.md
    - Lições Aprendidas: licoes-missao1.md
  - Missão 2:
    - SAFe: missao2-safe.md
    - Critérios de Aceitação: missao2-criterios-aceitacao.md
    - Requisitos Não Funcionais: rnf.md
    - Pontuação de US's: pontuacao.md
    - Priorização de US's: pontuacao.md
    - MVP: missao2-mvp.md
    - Lições Aprendidas: licoes-missao2.md

copyright: |
  REQ-2024.1 <a href="https://github.com/mdsreq-fga-unb/2024.1-ObjeX"  target="_blank" rel="noopener">CyberHunterz</a>